---
title: "section2_sitespecificData"
author: 'NYSDEC SMAS : Keleigh Reynolds'
date: "4/24/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
```

```{r include=FALSE}
#read in the standards table and chemistry table
stds<-read.csv(file.path(here::here(),
                         "data",
                         "standards",
                         "stds_use.csv"),
               stringsAsFactors = FALSE)

chem<-read.csv(file.path(here::here(),
                         "data",
                         "chemistry.csv"),stringsAsFactors = FALSE)

field<-read.csv(file.path(here::here(),
                          "data",
                          "insitu_chem.csv"),stringsAsFactors = FALSE)

bap<-read.csv(file.path(here::here(),
                        "data",
                        "metrics.csv"),stringsAsFactors = FALSE)
flow<-read.csv(file.path(here::here(),
                         "data",
                         "Wallkill_Flow_All.csv"),stringsAsFactors = FALSE)

site.loc<-read.csv(file.path(here::here(),
                             "data",
                            "sites_wallkill.csv"),stringsAsFactors = FALSE)

#make flow dates as dates:
flow$Date<-as.Date(flow$Date,"%m/%d/%Y")
```

```{r include=FALSE}
#get standards in for the field data
sites<-chem %>% 
  select(SITE_ID,SH_PWL_ID,SH_WQ_STANDARD) %>% 
  distinct()

field<-merge(field,sites, by="SITE_ID")

field$PARAMETER_NAME<-tolower(field$PARAMETER_NAME)
field$PARAMETER_NAME<-gsub("_"," ",field$PARAMETER_NAME)

field<-field %>% 
  select(SITE_ID,Date,PARAMETER_NAME,RESULT,unit,SH_WQ_STANDARD,SH_PWL_ID)

```

```{r include=FALSE}

#####THIS SECION should be accomplished with the stayCALM package eventualy, but for now this is manual.
#rename columns to merge
stds<-stds %>% 
  rename("SH_WQ_STANDARD"=Classification,
         "chemical_name"=parameter)

#make them both lowercase to match
stds$chemical_name<-tolower(stds$chemical_name)
chem$chemical_name<-tolower(chem$chemical_name)

#remove any chems that have R, reject, flags
chem<-chem %>% filter(validator_qualifiers!="R")
chem<-chem %>% filter(!is.na(result_value))

#make the name for phosphorus match
chem<-chem%>%
  mutate(chemical_name=case_when(
    chemical_name=="phosphorus, total (as p)"~ "phosphorus",
    TRUE ~ as.character(chemical_name)
  ))

```


```{r include=FALSE}
#merge them to have use, classfication and the thresholds, note this limits some of teh data set.#maybe we should keep them all?
chem.df<-merge(chem,stds, by=c("SH_WQ_STANDARD","chemical_name"),all.x = TRUE)

field<-field %>% 
  rename("chemical_name"=PARAMETER_NAME,
         "result_value"=RESULT)
  
insitu.df<-merge(field,stds, by=c("SH_WQ_STANDARD","chemical_name"),all.x = TRUE)


#check that result unit and wqs units are the same
#units<-chem.df %>% 
 # filter(result_unit!=units)

#most of the werent, so changing from mg/l to ug/l for the standards.

chem.df$corrected_value<-NA
insitu.df$corrected_value<-NA

#correct them based on the units in the stds, and convert corrected value column to numeric
chem.df$corrected_value<-ifelse(chem.df$result_unit=="mg/l" & chem.df$units=="ug/L",chem.df$result_value*1000,paste0(chem.df$result_value))
chem.df$corrected_value<-ifelse(is.na(chem.df$corrected_value),chem.df$result_value,chem.df$corrected_value)
chem.df$corrected_value<-as.numeric(chem.df$corrected_value)
insitu.df$corrected_value<-ifelse(insitu.df$unit=="mg/l" & insitu.df$units=="ug/L",insitu.df$result_value*1000,insitu.df$result_value)
insitu.df$corrected_value<-ifelse(is.na(insitu.df$corrected_value),insitu.df$result_value,insitu.df$corrected_value)
insitu.df$corrected_value<-as.numeric(insitu.df$corrected_value)


chem_short.df<-chem.df %>% 
  select(SITE_ID,sample_date,SH_WQ_STANDARD,chemical_name,result_value,corrected_value,result_unit,wqs.numeric,units,wqs.type,wqs.violation.direction,wqs.narrative,calculation.,params.for.calcs.1,params.for.calcs.2) %>% 
  rename("COLL_DATE"=sample_date) %>% 
  subset(wqs.type!="calculation"|is.na(wqs.type))

#separate out the ones that need to be calculated
chem_calcs.df<-chem.df %>% 
  select(SITE_ID,sample_date,SH_WQ_STANDARD,chemical_name,result_value,corrected_value,result_unit,wqs.numeric,units,wqs.type,wqs.violation.direction,wqs.narrative,calculation.,params.for.calcs.1,params.for.calcs.2) %>% 
  rename("COLL_DATE"=sample_date) %>% 
  filter(wqs.type=="calculation"|chemical_name=="coppper"|chemical_name=="zinc")

#create exceedance column
chem_short.df$exceed<-NA

chem_short.df$exceed<-ifelse(chem_short.df$wqs.violation.direction=="greater"& chem_short.df$corrected_value>chem_short.df$wqs.numeric|
                               chem_short.df$wqs.violation.direction=="less"& chem_short.df$corrected_value<chem_short.df$wqs.numeric,1,0)

#same for insitu data
insitu.df$exceed<-NA

insitu.df$exceed<-ifelse(insitu.df$wqs.violation.direction=="greater"& insitu.df$corrected_value>insitu.df$wqs.numeric|
                               insitu.df$wqs.violation.direction=="less"& insitu.df$corrected_value<insitu.df$wqs.numeric,1,0)

#now we have both data frames with exceedances!
```

```{r message=FALSE,warning=FALSE,include=FALSE}
#next calculations for other stuff
#first we need hardness

hardness<-chem %>% 
  filter(chemical_name=="hardness (as caco3)"&interpreted_qualifiers!="R") %>% 
  rename("COLL_DATE"=sample_date,
         "hardness_result"=result_value) %>% 
  select(SITE_ID,COLL_DATE,hardness_result) %>% 
  filter(!is.na(hardness_result)) %>% 
  distinct()
#change mg/L to PPM; so ppm basically equals mg/L, ppb is ug/L and so on

#merge the hardness values in here
calcs.df<-merge(chem_calcs.df,hardness,by=c("SITE_ID","COLL_DATE"))
calcs.df<-calcs.df %>% 
  distinct()

#now we need ph and temp for Nitrogen, field = insitu data
tnp<-field %>% 
  filter(chemical_name=="temperature"|chemical_name=="ph") %>% 
  tidyr::spread(chemical_name,result_value) %>% 
  select(SITE_ID,Date,ph,temperature) %>% 
  rename("COLL_DATE"=Date)

#collapse temp and ph into one line
#first transform from wide to long, and then back out to get it into one line
tnp$combo<-paste(tnp$SITE_ID,tnp$COLL_DATE,sep = "_")
tnp<-tnp %>% 
  group_by(combo) %>% 
  tidyr::gather(parameter,value,ph:temperature,na.rm=TRUE)
tnp<-tnp %>% 
  tidyr::spread(parameter,value)
  
calcs.df<-merge(calcs.df,tnp, by=c("SITE_ID","COLL_DATE"))
calcs.df<-calcs.df %>% 
  distinct()

#now we have all theinformation in one dataframe, let's do the calcs.

calcs.df<-calcs.df %>% 
  mutate(calc_value=case_when(
    chemical_name %in% "copper"~ 0.96*exp(0.9422*log(calcs.df$hardness_result)-1.7),
    chemical_name %in% "zinc" ~ exp(0.85*log(calcs.df$hardness_result)+0.5),
    #chemical_name %in% "nitrogen, ammonia (as n)"~ 1*calcs.df$corrected_value,
    chemical_name %in% "lead"~ 1.46203 - (log(calcs.df$hardness)*(0.145712))*exp(1.273* (log(calcs.df$hardness)) - 4.297),
    chemical_name %in% "nickel"~ 0.997*exp (0.846*log(calcs.df$hardness)) + 0.0584,
    TRUE ~ 0 #each of the things before the ~ is true or false, need to hit a true eventually working from top down %in% is better than ==
    #bc of NA's in the column
    #use this to correct in the units dplyr
  ))


calcs.df$exceedance<-NA
calcs.df$exceedance<-ifelse(calcs.df$corrected_value>calcs.df$calc_value,1,0)

```

```{r include=FALSE}
#now we need numeric nutrient criteria
nnc<-chem %>% 
  filter(chemical_name=="phosphorus" & interpreted_qualifiers!="R")

nnc<-nnc %>% 
  rename("DATE"=sample_date)
nnc$DATE<-as.Date(nnc$DATE,"%m/%d/%Y")
nnc$year<-format(nnc$DATE,"%Y")

cla<-chem %>% 
  filter(chemical_name=="chlorophyll a") %>% 
  select(SITE_ID,result_value,sample_date) %>% 
  rename("chla"=result_value,
         "DATE"=sample_date)
cla$DATE<-as.Date(cla$DATE,"%m/%d/%Y")
cla$year<-format(cla$DATE,"%Y")

#shorten the bap stuff
bap.1<-bap %>% 
  select(SITE_ID,MSSIH_EVENT_SMAS_SAMPLE_DATE,MMDH_BIO_ASMT_PROFILE_SCORE) %>% 
  rename(DATE=MSSIH_EVENT_SMAS_SAMPLE_DATE)
bap.1$DATE<-as.Date(bap.1$DATE,"%m/%d/%Y")
bap.1$year<-format(bap.1$DATE,"%Y")
#dates don't match exactly, so maybe we'll do bap by year?

#make bap scores by year
bap.1<-bap.1 %>% 
  select(SITE_ID,year,MMDH_BIO_ASMT_PROFILE_SCORE) %>% 
  group_by(SITE_ID,year) %>% 
  mutate(bap.scr=mean(MMDH_BIO_ASMT_PROFILE_SCORE))

#remove the individual bap's from the df
bap.1$MMDH_BIO_ASMT_PROFILE_SCORE<-NULL
bap.1<-bap.1 %>% 
  distinct()

#also need BAP for this one,first merge the nnc (phos) with the bap(by year)-some of these seem to be missing, they were listed as collected with LGSS low gradient, listed. so no bap's can be calculated
nnc.df<-merge(nnc,bap.1,by=c("SITE_ID","year"),all.x = TRUE)

#then merge with CLA for chlorophyll

nnc.df<-merge(nnc.df,cla,by=c("SITE_ID","DATE"), all.x = TRUE)
nnc.df<-nnc.df %>% 
  rename(MMDH_BIO_ASMT_PROFILE_SCORE=bap.scr)

nnc.df<-nnc.df %>% 
  select(SITE_ID,DATE,chemical_name,result_value,result_unit,SH_WQ_STANDARD,SH_PWL_ID,MMDH_BIO_ASMT_PROFILE_SCORE,chla)

#now do it by SH_WQ_STANDARD
#0.03 mg/L AND bap < 5 is phos nnc, if A, then also cla >6 ug/L

nnc.final.df<-nnc.df %>% 
  mutate(exceed=case_when(
    SH_WQ_STANDARD %in% "A"& result_value>0.025 & chla>6 ~ 1,
    SH_WQ_STANDARD %in% "B"& result_value>0.075 & MMDH_BIO_ASMT_PROFILE_SCORE<5 ~1,
    SH_WQ_STANDARD %in% "B(T)"& result_value>0.075 & MMDH_BIO_ASMT_PROFILE_SCORE<5 ~1,
    SH_WQ_STANDARD %in% "C"& result_value>0.075 & MMDH_BIO_ASMT_PROFILE_SCORE<5 ~1,
    TRUE ~ 0
  ))

#add note for misssing bap
nnc.final.df$exceed.note<-if_else(is.na(nnc.final.df$MMDH_BIO_ASMT_PROFILE_SCORE), paste("Missing BAP score."),paste(""))


```

```{r, message=FALSE,include=FALSE}
#then create summary columns for each type of data set
chem_short.df$corrected_value<-as.numeric(chem_short.df$corrected_value)

chem_sum.df<-chem_short.df %>% 
  group_by(SITE_ID,chemical_name) %>% 
  summarise(record_count=n(),mean=mean(corrected_value,na.rm =TRUE),num_exceed=sum(exceed),min=min(corrected_value,na.rm =TRUE),max=max(corrected_value,na.rm =TRUE),median=median(corrected_value,na.rm =TRUE))

chem_sum.df<-chem_sum.df %>% 
  mutate_if(is.numeric, round, 3)

  
#then create summary columns for the in-situ
insitu_sum.df<-insitu.df %>% 
  group_by(SITE_ID,chemical_name) %>% 
  summarize(record_count=n(),mean=mean(corrected_value,na.rm =TRUE),num_exceed=sum(exceed),min=min(corrected_value,na.rm =TRUE),max=max(corrected_value,na.rm =TRUE),median=median(corrected_value,na.rm =TRUE)) %>% 
  mutate_if(is.numeric, round, 3)

insitu.df<-insitu.df %>% 
  mutate_if(is.numeric, round, 3)
  

#and summary for the calcs
calcs.df$corrected_value<-as.numeric(calcs.df$corrected_value)
calcs_sum.df<-calcs.df %>% 
  group_by(SITE_ID,chemical_name) %>% 
  summarize(record_count=n(),mean=mean(corrected_value,na.rm =TRUE),num_exceed=sum(exceedance),min=min(corrected_value,na.rm =TRUE),max=max(corrected_value,na.rm =TRUE),median=median(corrected_value,na.rm =TRUE)) %>% 
  mutate_if(is.numeric, round, 3)

calcs_sum.df<-calcs_sum.df %>%
  mutate_if(is.numeric,round, 3)

calcs_sum.df<-calcs_sum.df %>%
  mutate_if(is.numeric,format, scientific=FALSE)
  
#and summary for the nnc
nnc_sum.df<-nnc.final.df %>% 
  group_by(SITE_ID,chemical_name) %>% 
  summarize(record_count=n(),mean=mean(result_value,na.rm =TRUE),num_exceed=sum(exceed),min=min(result_value,na.rm =TRUE),max=max(result_value),median=median(result_value,na.rm =TRUE))
  
nnc_sum.df<-nnc_sum.df %>% 
  mutate_if(is.numeric, round, 3)
  

#summary for the BAP
bap.df<-bap %>% 
  select(SITE_ID,MSSIH_EVENT_SMAS_SAMPLE_DATE,MMDH_BIO_ASMT_PROFILE_SCORE,year) %>% 
  rename(DATE=MSSIH_EVENT_SMAS_SAMPLE_DATE) %>% 
  filter(year=="2017"|year=="2018"|year=="2019") %>% 
  group_by(SITE_ID,DATE) %>% 
  summarize(BAP=mean(MMDH_BIO_ASMT_PROFILE_SCORE),SD=sd(MMDH_BIO_ASMT_PROFILE_SCORE),n=n())

bap.df<-bap.df%>% 
  mutate_if(is.numeric, round, 2)
            

```


```{r include=FALSE}
#FUNCTIONS

table.f<-function(df,x,y){
 
  tl<-flextable::flextable(df) %>% 
    flextable::font(i = NULL, j = NULL, fontname="Arial", part = "all") %>% 
    flextable::theme_zebra() %>% 
    flextable::autofit()
tl<- flextable::align(tl, i = NULL, j =(x:y) , align = "center", part = "all")
tl<-flextable::fit_to_width(tl,max_width = 6)
return(tl)
}

#map function
map.me<-function(df1,df2){
  #bounding box
library(ggmap)
nybox<-make_bbox(df1,lon=SH_LONGITUDE,lat=SH_LATITUDE)
 
ny.map<-qmap(nybox, source = "osm")+geom_point(data=df1,aes(x=SH_LONGITUDE,y=SH_LATITUDE),
                  color="yellow",size=4)+
  geom_point(data=df2,aes(x=SH_LONGITUDE,y=SH_LATITUDE),color="red",size=4)
print(ny.map)
  
}

#table.f<-function(df, center.cols){
 
 # tl<-flextable::flextable(df) %>% 
  #  flextable::font(i = NULL, j = NULL, fontname="Arial", part = "all") %>% 
   # flextable::theme_zebra() %>% 
    #flextable::autofit()
#tl<- flextable::align(tl, i = NULL, j = center.cols, align = "center", part = "all")
#return(tl)
#}
#table.f(mer_short.df, c("min", "max")) %>% 
 # flextable::align(i = NULL, j = "SITE_ID", align = "center", part = "all")

#x.vec
```

```{r,warning=FALSE, echo=FALSE,message=FALSE, results='asis',fig.align="left"}

sites<-unique(site.loc$SH_SITE_ID)

 for (i in seq_along(sites)) { 
   # print(i)
   cat("  \n\n### Site ID: ",sites[i])
   
   site.loc.small<-site.loc[site.loc$SH_SITE_ID %in% sites[i],]
   
   map.me(site.loc,site.loc.small)
  
  temp <-chem_sum.df[chem_sum.df$SITE_ID %in% sites[i], ]
   tab<-table.f(temp, 2,4)
   label=paste("Chemistry Measurements:",sites[i])
   tab<-flextable::set_caption(tab,label)
   flextable::docx_value(tab)
   flextable::fit_to_width(tab,max_width = 6)
   rm(temp)
   cat("  \n")
   cat("<br><br>")
   
  temp <-insitu_sum.df[insitu_sum.df$SITE_ID %in% sites[i], ]
   tab2<-table.f(temp, 2,4)
   label=paste("In-Situ Measurements:",sites[i])
   tab2<-flextable::set_caption(tab2,label)
   flextable::docx_value(tab2)
   rm(temp)
   cat(rep("\n", 10))
   cat("<br><br>")
   
  temp <-calcs_sum.df[calcs_sum.df$SITE_ID %in% sites[i], ]
   tab3<-table.f(temp, 2,4)
   label=paste("Dependent Measurements (Metals and Ammonia):",sites[i])
   tab3<-flextable::set_caption(tab3,label)
   flextable::docx_value(tab3)
   rm(temp)
   cat("  \n")
   cat("<br><br>")
   
  temp <-nnc_sum.df[nnc_sum.df$SITE_ID %in% sites[i], ]
   tab4<-table.f(temp, 2,4)
   label=paste("Numeric Nutrient Criteria:",sites[i])
   tab4<-flextable::set_caption(tab4,label)
   flextable::docx_value(tab4)
   rm(temp)
   cat("  \n")
   cat("<br><br>")
  
  temp<-bap.df[bap.df$SITE_ID %in% sites[i], ]
  tab6<-table.f(temp,1,2)
  label=paste("BAP Score: ",sites[i])
  tab6<-flextable::set_caption(tab6,label)
  flextable::docx_value(tab6)
  rm(temp)
  cat("  \n")
  cat("<br><br>")
  
  temp<-flow[flow$ID %in% sites[i], ]
  if (nrow(temp) > 0) {
    library(ggplot2)
    tab5<-ggplot(temp,aes(Date,Discharge..cfs.)) +
      geom_point()
    print(tab5)
    rm(temp)
  }


  cat("  \n")
  
 }

    
    # create plot for each PWL in df 
    
```


