---
title: "Section 1 a) chemistry and stream discharge"
author: 'NYSDEC SMAS : Keleigh Reynolds'
date: "4/10/2020"
output: 
word_document: default
---

```{r include=FALSE, message=FALSE,warning=FALSE}

#set up the file path
file.path=file.path(here::here(),
          "data",
          "chemistry.csv")

#for the table
file.path.1<-file.path(here::here(),
                       "data",
                       "qaqc_analyte_table.csv")

#for in-siture
file.path.2<-file.path(here::here(),
                       "data",
                       "insitu_chem.csv")

file.path.3<-file.path(here::here(),
                       "data",
                       "sbu.chem.all.csv")
```

```{r include=FALSE,message=FALSE,warning=FALSE}
#Read in the data needed for the section

#analyte table
analyte<-read.csv(file.path.1,stringsAsFactors = FALSE)

#read in the chemistry file
chem_all<-read.csv(file.path,stringsAsFactors = FALSE)

#read in the sites table
sites<-read.csv(file.path(here::here(),
                          "data",
                          "sites_wallkill.csv"),stringsAsFactors = FALSE)

#read in the in-siture data
insitu<-read.csv(file.path.2,stringsAsFactors = FALSE)
          
```

## Analyte Table

```{r tab.id= "Analytes", tab.cap="Water chemistry analytes sampled as part of the Wallkill River Stream Assessment Survey. Table lists sampled analytes and analytical specifications. ^ Precision objectives are defined by results of duplicate samples as described in Appendix III", echo=FALSE, message=FALSE, warning=FALSE}

library(dplyr)
library(flextable)

#create table for the analyte list/precision method etc
tl.1<-analyte %>% 
  rename("Analytical \nLab"=Analytical.Lab,
         "Method"=Standard.Method,
         "Calibration: \n Initial"=Cal.initial,
         "Calibration: \n Ongoing"=cal.ongoing,
         "Calibration: \n Blanks"=cal.blanks,
         "Detection \n Limit"=Method.Detection.Limit,
         "Reporting \n Limit"=Reporting.Limit)


tl.1<-flextable(tl.1) %>% 
  font(i = NULL, j = NULL, fontname="Arial", part = "all") %>% 
  theme_zebra() %>% 
  fontsize(size = 8, part="all")%>%
  autofit()
tl.1<-align(tl.1, i = NULL, j =(2:10) , align = "center", part = "all")%>%
  width(j=c(6:10), width = 0.8)%>%
  width(j=3:5, width=0.6)%>%
  width(j=1, width=1.2)
tl.1

```
\newpage
## Water Chemistry by PWL ID

```{r include=FALSE,message=FALSE,warning=FALSE}
#adding statewide stuff to the graphs
chem.everywhere<-read.csv(file.path.3,stringsAsFactors = FALSE)

#limit to just eh columns we need
chem.everywhere<-chem.everywhere %>% 
  select(CHR_CHEMICAL_NAME,CHR_RESULT_VALUE,CHR_RESULT_UNIT,CHR_VALIDATOR_QUAL)

#take out the ones that were flagged as rejected
chem.statewide<-chem.everywhere %>% 
  filter(CHR_VALIDATOR_QUAL!="R")

#summarize for statwide averages
chem.statewide<-chem.statewide %>%
  group_by(CHR_CHEMICAL_NAME) %>% 
  summarise_at(vars(CHR_RESULT_VALUE),funs(mean(.,na.rm = TRUE),sd(.,na.rm = TRUE),n=n(),q95=quantile(CHR_RESULT_VALUE,.95,na.rm = TRUE),q75=quantile(CHR_RESULT_VALUE,.75,na.rm = TRUE),q50=quantile(CHR_RESULT_VALUE,.50,na.rm=TRUE),q25=quantile(CHR_RESULT_VALUE,.25,na.rm = TRUE)))

#confidence intervals
chem.statewide.2<-chem.statewide %>% 
  #mutate(error=(qnorm(0.975)*sd/sqrt(n)),ci95=mean+error,ci.neg95=mean-error)#this is the confidense interval
  mutate(q95=quantile(chem.statewide$CHR_RESULT_VALUE,.95),q75=quantile(chem.statewide$CHR_RESULT_VALUE,.75),)

#now limit it to just the chemistry we have on hand

chem.short<-chem_all %>% 
  select(chemical_name) %>% 
  distinct() 

chem.short$chemical_name<-tolower(chem.short$chemical_name)
  
chem.short.l<-unique(chem.short$chemical_name)

chem.statewide<-chem.statewide %>% 
  filter(CHR_CHEMICAL_NAME %in% chem.short.l)

#change names to match

chem.statewide<-chem.statewide%>%
  mutate(CHR_CHEMICAL_NAME=case_when(
    CHR_CHEMICAL_NAME=="chloride (as cl)"~ "Chloride",
    CHR_CHEMICAL_NAME=="hardness (as caco3)" ~"Hardness (as CaCO3)",
    CHR_CHEMICAL_NAME=="nitrogen, nitrate (as n)" ~"Nitrate",
    CHR_CHEMICAL_NAME=="nitrogen, nitrite" ~ "Nitrite",
    CHR_CHEMICAL_NAME=="phosphorus, total (as p)" ~ "Total Phosphorus",
    CHR_CHEMICAL_NAME=="total dissolved solids (residue, filterable)" ~ "Total Dissolved Solids",
    CHR_CHEMICAL_NAME=="alkalinity, total (as caco3)" ~ "Alkalinity",
    CHR_CHEMICAL_NAME=="nitrogen, kjeldahl, total" ~ "Total Kjeldahl Nitrogen",
    CHR_CHEMICAL_NAME=="nitrate+nitrite as nitrogen" ~ "Nitrate+Nitrite",
    CHR_CHEMICAL_NAME=="nitrogen, ammonia (as n)" ~ "Ammonia",
    CHR_CHEMICAL_NAME=="turbidity" ~ "Turbidity",
    CHR_CHEMICAL_NAME=="aluminum" ~ "Aluminum",
    CHR_CHEMICAL_NAME=="arsenic" ~ "Arsenic",
    CHR_CHEMICAL_NAME=="cadmium" ~ "Cadmium",
    CHR_CHEMICAL_NAME=="calcium" ~ "Calcium",
    CHR_CHEMICAL_NAME=="chlorophyll a" ~ "Chlorophyll A",
    CHR_CHEMICAL_NAME=="copper" ~ "Copper",
    CHR_CHEMICAL_NAME=="iron" ~ "Iron",
    CHR_CHEMICAL_NAME=="lead" ~ "Lead",
    CHR_CHEMICAL_NAME=="magnesium" ~ "Magnesium",
    CHR_CHEMICAL_NAME=="nickel" ~ "Nickel",
    CHR_CHEMICAL_NAME=="silver" ~ "Silver",
    CHR_CHEMICAL_NAME=="zinc" ~ "Zinc",
    TRUE ~ as.character(CHR_CHEMICAL_NAME)
  ))

```


```{r include=FALSE,message=FALSE,warning=FALSE}

#Chemistry figures for each analyte
library(stringr)
library(reshape2)
library(ggplot2)
library(ggthemes)
library(pander)
library(dplyr)
library(forcats)

chem_all$SH_PWL_ID<-as.factor(chem_all$SH_PWL_ID)
#take out the Rejected samples
chem_all<-chem_all %>% 
  filter(chem_all$validator_qualifiers!="R")

#merge with sites to get the order
#first just grab what we need
sites.1<-sites %>% 
  select(order,group,SH_SITE_ID) %>% 
  rename("SITE_ID"=SH_SITE_ID)

chem_all<-merge(chem_all,sites.1,by="SITE_ID")

#create units column
chem.trans<-subset(chem_all,chem_all$result_unit=="mg/l"|chem_all$result_unit=="ug/l"|chem_all$result_unit=="ntu")
chem.trans<-chem.trans %>% 
   arrange(order)

chem.trans$SH_PWL_ID<-fct_reorder(chem.trans$SH_PWL_ID, chem.trans$order)


chem.trans<-chem.trans%>%
  mutate(chemical_name=case_when(
    chemical_name=="CHLORIDE (AS CL)"~ "Chloride",
    chemical_name=="HARDNESS (AS CACO3)" ~"Hardness (as CaCO3)",
    chemical_name=="NITROGEN, NITRATE (AS N)" ~"Nitrate",
    chemical_name=="NITROGEN, NITRITE" ~ "Nitrite",
    chemical_name=="PHOSPHORUS, TOTAL (AS P)" ~ "Total Phosphorus",
    chemical_name=="TOTAL DISSOLVED SOLIDS (RESIDUE, FILTERABLE)" ~ "Total Dissolved Solids",
    chemical_name=="ALKALINITY, TOTAL (AS CaCO3)" ~ "Alkalinity",
    chemical_name=="NITROGEN, KJELDAHL, TOTAL" ~ "Total Kjeldahl Nitrogen",
    chemical_name=="Nitrate+Nitrite as Nitrogen" ~ "Nitrate+Nitrite",
    chemical_name=="Nitrogen, ammonia (As N)" ~ "Ammonia",
    chemical_name=="TURBIDITY" ~ "Turbidity",
    TRUE ~ as.character(chemical_name)
  ))%>%
  filter(chemical_name!="Nitrogen")


```

```{r chemgraph1, echo=FALSE, fig.width=6, fig.height=4, message=FALSE, warning=FALSE, fig.cap=paste(unique(chem.trans$chemical_name), ", " , "The X-axis presents WI/PWL ID of the sampling locations from upstream to downstream and axis labels correspond with Table 1, Figure 1 and Figure 2. Color of the box represents the location of the WI/WPL in the watershed as indicated in the plot legend. Horizontal lines represent the 95th, 75th, and 25th percentiles of statewide data for each endpoint. The total number of reported values illustrated for each sampling location can vary due to non-detection and QA/QC procedures. Descriptions of removed records are presented in Appendix III.", sep="")}
# create graphing function for those that need to be log10 (ug/L or mg/l-so not weird ones)
chem.graph <- function(df, na.rm = TRUE, ...){
  
  # create list of chmistry's in data to loop over 
  chem_list <- unique(df$chemical_name)
  l<-length(chem_list)
  for (i in seq_along(chem_list)) { 
    #order by group
    df<-df %>% 
       arrange(order)
    
    temp.statewide<-subset(chem.statewide,chem.statewide$CHR_CHEMICAL_NAME==chem_list[i])
    
    # create plot for each PWL in df 
    plot <- 
      ggplot(subset(df, df$chemical_name==chem_list[i]),
             aes(SH_PWL_ID,result_value,group=SH_PWL_ID,color=group))+ 
      
      geom_boxplot() +

      #scale_shape_manual(name="PWL Segment ID",values = 0:max(l))+
      
      theme_pander() +
      theme(axis.text.x = element_text(angle = 60, hjust = 1))+
      theme(legend.position="right") + 
      
      scale_y_log10(paste(df$chemical_name[df$chemical_name==chem_list[i]], df$result_unit[df$chemical_name==chem_list[i]], "log(10)")) + 
      xlab("Location ID")+
      geom_hline(yintercept=temp.statewide$q95,color="grey53")+
      geom_hline(yintercept=temp.statewide$q75,color="grey53")+
       geom_hline(yintercept=temp.statewide$q25,color="grey53")+
      annotate(geom="text", label="95th", x=2, y=temp.statewide$q95, vjust=-1,color="grey")+
    annotate(geom="text", label="75th", x=2, y=temp.statewide$q75, vjust=-1,color="grey")+
    annotate(geom="text", label="25th", x=2, y=temp.statewide$q25, vjust=-1,color="grey")
    
    
    # print plots to screen
    print(plot)
    cat('\n\n') 
    
  }
  
  
}

chem.graph(chem.trans) 

```



```{r insituChem, echo=FALSE, fig.width=6, fig.height=4, message=FALSE, warning=FALSE, fig.cap=paste(unique(insitu.short$PARAMETER_NAME), ", " , "The X-axis presents WI/PWL ID of the sampling locations from upstream to downstream and axis labels correspond with Table 1, Figure 1 and Figure 2. Color of the box represents the location of the WI/WPL in the watershed as indicated in the plot legend. Horizontal lines represent the 95th, 75th, and 25th percentiles of statewide data for each endpoint. The total number of reported values illustrated for each sampling location can vary due to non-detection and QA/QC procedures. Descriptions of removed records are presented in Appendix III.", sep="")}

#this one for the other values (no transformation of units-In-SITU data)

# create graphing function for those that don't need to be log10
#Chemistry, no transformation of results (in-situ)

#first get the sites and data we want.
sites.l<-unique(sites$SH_SITE_ID)

insitu.short<-insitu %>% 
  filter(SITE_ID %in% sites.l)
#merge to get the order/group/PWL

insitu.short<-merge(insitu.short,sites,by.x="SITE_ID",by.y="SH_SITE_ID")

#arrange them according to group and PWL
insitu.short$SH_PWL_ID<-fct_reorder(insitu.short$SH_PWL_ID, insitu.short$order)

insitu.short<-insitu.short %>% arrange(order)


#get the statwide values for these as well############################################
#limit to just eh columns we need
insitu.statewide<-insitu %>% 
  select(PARAMETER_NAME,RESULT,VALIDATOR_QUAL)

#summarize for statwide averages
insitu.statewide<-insitu.statewide %>%
  group_by(PARAMETER_NAME) %>% 
  summarise_at(vars(RESULT),funs(mean(.,na.rm = TRUE),sd(.,na.rm = TRUE),n=n(),q95=quantile(RESULT,.95,na.rm = TRUE),q75=quantile(RESULT,.75,na.rm = TRUE),q50=quantile(RESULT,.50,na.rm=TRUE),q25=quantile(RESULT,.25,na.rm = TRUE)))

#confidence intervals
#insitu.statewide<-insitu.statewide %>% 
  #mutate(error=(qnorm(0.975)*sd/sqrt(n)),ci95=mean+error,ci.neg95=mean-error)


chem.graph.n <- function(df, na.rm = TRUE, ...){

# create list of chmistry's in data to loop over 
chem_list.2 <- unique(df$PARAMETER_NAME)
for (i in seq_along(chem_list.2)) { 

#create dataframe for statewide
  temp.insitu.sw<-subset(insitu.statewide,insitu.statewide$PARAMETER_NAME==chem_list.2[i])

# create plot for each parameter with PWL in df 
 plot <- 
   ggplot(subset(df, df$PARAMETER_NAME==chem_list.2[i]),
    aes(SH_PWL_ID,RESULT,group=SH_PWL_ID,color=group))+ 

  geom_boxplot() +

 theme_pander() +
 theme(axis.text.x = element_text(angle = 60, hjust = 1))+
theme(legend.position="right") + 

 scale_y_continuous(paste(df$PARAMETER_NAME[df$PARAMETER_NAME==chem_list.2[i]],df$unit[df$PARAMETER_NAME==chem_list.2[i]])) + 
 xlab("Location ID")+
        geom_hline(yintercept=temp.insitu.sw$q95,color="grey53")+
      geom_hline(yintercept=temp.insitu.sw$q75,color="grey53")+
       geom_hline(yintercept=temp.insitu.sw$q25,color="grey53")+
       annotate(geom="text", label="95th", x=2, y=temp.insitu.sw$q95, vjust=-1,color="grey")+
    annotate(geom="text", label="75th", x=2, y=temp.insitu.sw$q75, vjust=-1,color="grey")+
    annotate(geom="text", label="25th", x=2, y=temp.insitu.sw$q25, vjust=-1,color="grey")
    


# print plots to screen
 print(plot)

cat('\n\n')   
 }

}

 
chem.graph.n(insitu.short)

```




