---
title: "section1_General"
author: 'NYSDEC SMAS : Keleigh Reynolds'
date: "4/14/2020"
output: 
word_document: default
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE,message=FALSE,warning=FALSE}

file.path.s=file.path(here::here(),
          "data",
          "sites_wallkill.csv")

sites<-read.csv(file.path.s,stringsAsFactors = FALSE)

```


```{r include=FALSE,message=FALSE,warning=FALSE}
#Table 1
#renames column in the sites table to match
library(dplyr)

table1<-sites %>% 
select(SH_SITE_ID,group,SH_RIVMILE,SH_PWL_ID,SH_WQ_STANDARD,SH_DESC,SH_LATITUDE,SH_LONGITUDE,order) %>% 
  distinct() %>% 
  arrange(order)

table1<-table1 %>% rename("Location ID"=SH_SITE_ID,
                          "Group"=group,
                  "Rivermile"=SH_RIVMILE,
                  "WI/PWL"=SH_PWL_ID,
                  "Waterbody Classification"=SH_WQ_STANDARD,
                  "Description"=SH_DESC,
                  "Latitude"=SH_LATITUDE,
                  "Longitude"=SH_LONGITUDE)

table1$Description<-toupper(table1$Description)

#remove order column for table disply
table1$order<-NULL

table1<-table1 %>% 
  rename("Waterbody \n Classification"=`Waterbody Classification`)


```

```{r tab.id="sites-table",  echo=FALSE, message=FALSE, warning=FALSE, tab.cap="Wallkill River (WALK) sampling locations. Locations are ordered from upstream to downstream according to river mile and mainstem confluence"}
library(flextable)
tl<-flextable(table1) %>% font(i = NULL, j = NULL, fontname="Arial", part = "all") %>% theme_zebra() %>% autofit()
tl<-align(tl, i = NULL, j =(2:5) , align = "center", part = "all")%>%
  fontsize(size=10, part = "all")%>%
  fontsize(j=6, size=8)%>%
  width(j=c(1), width=1.3)%>%
  width(j=c(5), width=1.1)%>%
  width(j=c(4), width=0.8)%>%
  width(j=c(2), width=0.5)%>%
  width(j=6, width=1.5)
tl
```

```{r include=FALSE,message=FALSE,warning=FALSE}

#Saving this section for later, needs work.
#library(ggplot2)
#library(ggmap)


#ny<-map_data("state")
#ny<-ny %>% filter(region=="new york") %>% 
  #filter(long>74.5,lat<42.5)
#counties <- map_data("county")
#ny_county <- subset(counties, region == "new york")

#ny.map<-ggplot(ny) + 
  #geom_polygon(aes(x = long, y = lat),fill=NA,color="black")
  
#ny.new<-ny.map+geom_point(data=sites.df,aes(x=SH_LONGITUDE,y=SH_LATITUDE),color="red",size=4)+
  #geom_text(data=sites.df,aes(x=SH_LONGITUDE,y=SH_LATITUDE,label=paste(as.character(SH_SITE_ID))),color="black")


```

```{r site-map, fig.cap="Map of Wallkill River (WALK) sampling locations. Site names reference the Location ID and River Mile presented in \\@ref(tab:sites-table)", echo=FALSE, message=FALSE, warning=FALSE}
#library(leaflet)
#m<-sites %>% 
 # distinct(SH_SITE_ID,SH_LATITUDE,SH_LONGITUDE)

#pop<-paste(sep = "<br/>",sites$SH_SITE_ID,sites$group,sites$order)

#map<-leaflet(m) %>%
 # addTiles() %>%  # Add default OpenStreetMap map tiles
  #addMarkers(~SH_LONGITUDE,~SH_LATITUDE, popup=~pop)
#map
```







