---
title: "section1C_stream_reach_physical_char"
author: 'NYSDEC SMAS : Keleigh Reynolds'
date: "4/16/2020"
output:
  word_document: default
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)

#set up the file path
file.path.h=file.path(here::here(),
          "data",
          "habitat_wk.csv")

file.path.s<-file.path(here::here(),
                       "data",
                       "sites_wallkill.csv")

```

```{r include=FALSE,message=FALSE,warning=FALSE}
#function to make the sites a factor in order from upstream to downstream
order_sites<-function(df, sites_table, df_site_col, sites_site_col){
Sites<-sites_table%>%
  dplyr::rename(SITE_ID=sites_site_col)

df<-df%>%
  dplyr::rename(SITE_ID=df_site_col)

all_data<-left_join(df, Sites)
all_data<-all_data%>%
  dplyr::arrange(order)%>%
  dplyr::mutate(SITE_ID=factor(SITE_ID, levels = unique(SITE_ID)))

columns<-colnames(Sites)
columns<-columns[!(columns %in% "SITE_ID")]

all_data<-all_data%>%
  dplyr::select(!tidyselect::any_of(columns))
}
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#read in the habitat data
habit<-read.csv(file.path.h,stringsAsFactors = FALSE)

#select relevant columns
habit<-habit %>% 
  select("Location ID" =SITE_ID, "Collection \n Date"=COLL_DATE, "Gradient"=HFDH_GRADIENT, "Epi.\n Cover"=HFDH_EPIFAUNAL_COVER, "Embed. \n Pool."=HFDH_EMBEDDEDNESS_POOLING, "Vel/Dep. \n Reg"=HFDH_VELOCITY_DEPTH_REGIME,
         "Sed. \n Dep."=HFDH_SEDIMENT_DEPOSITION, "Flow \n Status"=HFDH_FLOW_STATUS, "Chan. \n Alt"=HFDH_CHANNEL_ALTERATION, "Rif. \n Freq"=HFDH_RIFFLE_BEND_FREQUENCY) 

library(lubridate)
habit<-habit %>% 
  mutate(year=year(`Collection \n Date`))

#limit to last 3 years

habit<-habit %>% 
  filter(year >= 2017)

#read in sites table and reorder sites upstream to downstream
sites<-read.csv(file.path.s,stringsAsFactors = FALSE)

habit<-habit%>%
  order_sites(sites_table = sites, df_site_col = "Location ID", sites_site_col = "SH_SITE_ID")

habit$year<-NULL

#Average all entries per site
habit<-habit%>%
  group_by(SITE_ID, Gradient)%>%
  summarize(`Epi.\n Cover`=mean(`Epi.\n Cover`),
            `Embed. \n Pool.`=mean(`Embed. \n Pool.`),
            `Vel/Dep. \n Reg.`=mean(`Vel/Dep. \n Reg`),
            `Sed. \n Dep.`=mean(`Sed. \n Dep.`),
            `Flow \n Status`=mean(`Flow \n Status`),
            `Chan. \n Alt`=mean(`Chan. \n Alt`),
            `Rif. \n Freq`=mean(`Rif. \n Freq`))

```

```{r tab.id="Habitat-table", tab.cap="Ranked habitat characteristics and calculated HMA for the Wallkill River Survey, 2017-2019. Epifaunal substrate (Epi. Cover); Embeddedness/Pool Substrate Characterization (Embed. Pool.); Velocity Depth Regime/Pool Variability (Vel/Dep Reg.); Sediment Deposition (Sed. Dep.); Channel Flow Status (Flow Status); Channel Alteration (Chan. Alt.); Riffle Frequency/Stream Sinuosity (Rif. Freq.)", echo=FALSE, message=FALSE,warning=FALSE}
#table

#create function for common tables
#df is the data frame, x and y are the column numbers you want centered, z is the caption
table.f<-function(df,x,y){
 library(flextable)
  tl<-flextable(df) %>% font(i = NULL, j = NULL, fontname="Arial", part = "all") %>% theme_zebra() %>% autofit()
tl<-align(tl, i = NULL, j =(x:y) , align = "center", part = "all")
tl
}

#call the function
tl<-table.f(habit,2,9)


#this part might have to be figured out later, with a larger caption/table function? Not sure yet.


tl<-tl%>%
  width(j=2:9, width=0.7)
tl

```


