---
title: "Section 1 d)Observer Ranking of Recreational Ability"
author: "ALC"
date: "4/16/2020"
output:
  word_document: default
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(magrittr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(tidyselect)
library(flextable)

knitr::opts_chunk$set(echo = TRUE)

#set up the file path
file.path=file.path(here::here(),
          "data",
          "userp_wallkill.csv")

file.path2=file.path(here::here(),
          "data",
          "sites_wallkill.csv")

```

```{r echo=FALSE,message=FALSE,warning=FALSE}
#read in the data
UserP_all<-read.csv(file.path,stringsAsFactors = FALSE)%>%
  select(-X)
Sites<-read.csv(file.path2,stringsAsFactors = FALSE)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
#function to make the sites a factor in order from upstream to downstream
order_sites<-function(df, sites_table, df_site_col, sites_site_col){
Sites<-sites_table%>%
  dplyr::rename(SITE_ID=sites_site_col)

df<-df%>%
  dplyr::rename(SITE_ID=df_site_col)

all_data<-left_join(df, Sites)
all_data<-all_data%>%
  dplyr::arrange(order)%>%
  dplyr::mutate(SITE_ID=factor(SITE_ID, levels = unique(SITE_ID)))

columns<-colnames(Sites)
columns<-columns[!(columns %in% "SITE_ID")]

all_data<-all_data%>%
  dplyr::select(!tidyselect::any_of(columns))
}
```


```{r echo=FALSE,message=FALSE,warning=FALSE}

contact<-UserP_all%>%
  filter(UPFDH_PRIMARY_CONTACT!="")%>%
  filter(UPFDH_SECONDARY_CONTACT!="")%>%
  mutate(Primary=as.numeric(as.factor(UPFDH_PRIMARY_CONTACT)),
         Secondary=as.numeric(as.factor(UPFDH_SECONDARY_CONTACT)))%>%
  select(SITE_ID, Primary, Secondary)%>%
  pivot_longer(-SITE_ID, names_to = "Contact Type", values_to = "value")%>%
  order_sites(sites_table = Sites, sites_site_col = "SH_SITE_ID", df_site_col = "SITE_ID")


plot<-ggplot(contact, aes(x=SITE_ID, y=value, fill=`Contact Type`))+
  geom_bar(position="dodge", width=0.7, na.rm = TRUE, stat = "summary", fun.y = "mean")+
  ylab("Mean Observer Ranking")+
  xlab("Location ID")+
  ylim(0,6)+
  scale_fill_grey()+
  theme_pander() +
      theme(axis.text.x = element_text(angle = 60, hjust = 1))+
      theme(legend.position="right")

```

```{r  userP-rank, fig.cap="Mean observer ranking of recreational ability for Wallkill River sampling locations. Columns represent observer rankings for the desire to participate in 1° and 2° contact recreation. Ranking of recreation ability was performed for all locations during each site visit." , fig.width=7, fig.height=4, echo=FALSE, message=FALSE,warning=FALSE}
plot
```


```{r echo=FALSE,message=FALSE,warning=FALSE}
#create table of mean scores for Variables influencing recreation

Variables<-UserP_all%>%
  group_by(SITE_ID)%>%
  summarize(`Water Clarity`=round(mean(UPFDH_WATER_CLARITY, na.rm = TRUE), digits=0),
            `Suspended Phytoplankton`= round(mean(UPFDH_SUSP_PHYTOPLANKTON, na.rm = TRUE),digits=0),
            Periphyton= round(mean(UPFDH_PERIPHYTON, na.rm = TRUE), digits=0),
            Macrophyte= round(mean(UPFDH_MACROPHYTE, na.rm = TRUE), digits=0),
            Odor=round(mean(UPFDH_ODOR, na.rm=TRUE), digits=0),
            Trash= round(mean(UPFDH_TRASH, na.rm = TRUE), digits=0),
            `Discharge Pipes`= round(mean(UPFDH_DISCHARGE_PIPE, na.rm = TRUE), digits=0))%>%
  order_sites(sites_table=Sites, sites_site_col = "SH_SITE_ID", df_site_col = "SITE_ID")
```

```{r UserP-mean-factor, echo=FALSE, message=FALSE,warning=FALSE}
final_table<-flextable(Variables)%>%
  theme_zebra()%>%
  set_header_labels(SITE_ID="Site \n ID", `Water Clarity`="Water \n Clarity", `Suspended Phytoplankton`="Suspended \nPhytoplankton", Periphyton="Periphyton", Odor="Odor", Trash="Trash", `Discharge Pipes`= "Dishcarge \n Pipes")%>%
  align(j=2:8, align="center", part="all")%>%
  font(fontname = "Arial", part="all")%>%
  fontsize(size=10, part="all")%>%
  width(j = c(2,4,8), width = 0.8)%>%
  width(j = c(3,5), width = 1.1)%>%
  width(j=1, width=1.1)%>%
  set_caption(caption="Table:(\\#tab:UserP-mean-factor) Mean observer ranked value for factors influencing desire to participate in 1° and 2° contact recreation in the Wallkill River. Factors were ranked on a 10 scale (0 – Best/Natural; 10 Worst/Severe) according to perceived impact on a location. Ranking of recreation ability was performed for all locations during each site visit")

final_table
```



```{r echo=FALSE,message=FALSE,warning=FALSE}

DominantP<-UserP_all%>%
  filter(UPFDH_PRIMARY_VARIABLE!="")%>%
group_by(SITE_ID, UPFDH_PRIMARY_VARIABLE)%>%
  count()%>%
  group_by(SITE_ID)%>%
  filter(n == max(n))%>%
  group_by(SITE_ID)%>%
  summarize(Primary=paste0(UPFDH_PRIMARY_VARIABLE, collapse = ", "))
  
DominantS<-UserP_all%>%
  filter(UPFDH_SECONDARY_VARIABLE!="")%>%
group_by(SITE_ID, UPFDH_SECONDARY_VARIABLE)%>%
  count()%>%
  group_by(SITE_ID)%>%
  filter(n == max(n))%>%
  group_by(SITE_ID)%>%
  summarize(Secondary=paste0(UPFDH_SECONDARY_VARIABLE, collapse=", "))

Dominant<-left_join(DominantP, DominantS, by="SITE_ID")%>%
  order_sites(sites_table=Sites, sites_site_col = "SH_SITE_ID", df_site_col = "SITE_ID")



```

```{r UserP-dominant-factor, message = F, warning = F, echo= F}
final_table2<-flextable(Dominant)%>%
  theme_zebra()%>%
  align(j=1:3, align="left", part="all")%>%
  fontsize(size = 10, part = "body")%>%
  font(fontname = "Arial", part="all")%>%
  autofit()%>%
  set_caption(caption="Table:(\\#tab:UserP-dominant-factor) Most frequently ranked factor influencing observer desire to participate in 1° and 2° contact recreation in the Wallkill River. Factors influencing desire to recreate were ranked and a primary factor influencing the desire to participate in 1° and 2° contact recreation was chosen during each site visit. Column values represent the factor selected most frequently at each site.")

final_table2
```


